/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'thatsIch' at '30.07.16 19:14' with Gradle 2.7
 *
 * @author thatsIch, @date 30.07.16 19:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
